kerimovscreations/ML-For-Beginners-AZ

- 2-Regression/1-Tools/translations/README.az.md
- 2-Regression/1-Tools/translations/assignment.az.md
- 2-Regression/translations/README.az.md
Added AZ Translations for chapter 2.1(Regression/Tools)
> AZ translation for 2.1 added

- 2-Regression/4-Logistic/translations/README.az.md
- 2-Regression/4-Logistic/translations/assignment.az.md
> AZ translation for 2.4

- 2-Regression/3-Linear/translations/README.az.md
- 2-Regression/3-Linear/translations/assignment.az.md
> AZ translation for 2.3

- 2-Regression/1-Tools/translations/README.az.md
- 2-Regression/2-Data/translations/README.az.md
- 2-Regression/2-Data/translations/assignment.az.md
- 2-Regression/translations/README.az.md
> AZ translation for 2.2

- 4-Classification/1-Introduction/translations/README.az.md
- 4-Classification/1-Introduction/translations/assignment.az.md
- 4-Classification/translations/README.az.md
> Add AZ translation for section 4.1

- 4-Classification/3-Classifiers-2/translations/README.az.md
- 4-Classification/3-Classifiers-2/translations/assignment.az.md
> AZ translation for 4.3

- 4-Classification/2-Classifiers-1/translations/README.az.md
- 4-Classification/2-Classifiers-1/translations/assignment.az.md
> AZ translation for 4.2

- 1-Introduction/3-fairness/translations/README.az.md
- 1-Introduction/3-fairness/translations/assignment.az.md
> AZ translation for 1.3

- 4-Classification/4-Applied/translations/README.az.md
- 4-Classification/4-Applied/translations/assignment.az.md
> Translation AZ 4.4

- 6-NLP/1-Introduction-to-NLP/translations/README.az.md
- 6-NLP/1-Introduction-to-NLP/translations/assignment.az.md
> AZ translation for 6.1

- 6-NLP/3-Translation-Sentiment/translations/README.az.md
- 6-NLP/3-Translation-Sentiment/translations/assignment.az.md
Translation added for 6.3
Solves #29
> Translation: AZE 6.3

- 7-TimeSeries/3-SVR/translations/README.az.md
- 7-TimeSeries/3-SVR/translations/assignment.az.md
> AZ: added translation for 7.3

- 9-Real-World/1-Applications/translations/README.az.md
- 9-Real-World/1-Applications/translations/assignment.az.md
- 9-Real-World/translations/README.az.md
> AZ: added translation for 9.1

- 8-Reinforcement/1-QLearning/translations/README.az.md
- 8-Reinforcement/1-QLearning/translations/assignment.az.md
> AZ Translation for 8.1

- 8-Reinforcement/1-QLearning/translations/assignment.az.md
- 8-Reinforcement/2-Gym/translations/README.az.md
- 8-Reinforcement/2-Gym/translations/assignment.az.md
> AZ Translation for 8.2

- 9-Real-World/2-Debugging-ML-Models/translations/README.az.md
- 9-Real-World/2-Debugging-ML-Models/translations/assignment.az.md
> AZ: added translation for 9.2

- translations/README.az.md
> AZ translation for README.md

- 6-NLP/4-Hotel-Reviews-1/translations/README.az.md
- 6-NLP/4-Hotel-Reviews-1/translations/assignment.az.md
> Translate section 6.4 into Azerbaijani

- quiz-app/src/App.vue
- quiz-app/src/assets/translations/az.json
- quiz-app/src/assets/translations/index.js
> TRANS-AZ: added quiz translation

- 6-NLP/3-Translation-Sentiment/translations/README.az.md
- 6-NLP/3-Translation-Sentiment/translations/assignment.az.md
> TRANS-AZ: completed the translation of section 6.3 into AZ
